apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: java
        image: sri3050/java:v1
        ports:
        - containerPort: 8080
