name: Maven Build

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build and push to ECR
        run: |
          docker build -t ${{ vars.IMAGE_NAME }}/${{ vars.REPO_NAME }}:${{ github.sha }} .
          docker push ${{ vars.IMAGE_NAME }}/${{ vars.REPO_NAME }}:${{ github.sha }}
      - name: update kube config fie
        run: aws eks update-kubeconfig --name eks-cluster --region us-west-2
      - name: Deploy to eks
        run: kubectl apply -f pod.yml
      - name: creating a deploy buy using image
        run: kubectl create deploy dep1 --image ${{ vars.IMAGE_NAME }}/${{ vars.REPO_NAME }}:${{ github.sha }} --replicas=1 --dry-run=client -o yaml>dep.yml
      




