name: Maven Build

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker image
        run: |
          docker build -t ${{ var.IMAGE_NAME }}/${{ var.REPO_NAME }}:${{ github.sha }} .
          docker push ${{ var.IMAGE_NAME }}/${{ var.var.REPO_NAME }}:${{ github.sha }}
      - name: Output pushed image
        run: echo "pushed image ${{ var.IMAGE_NAME }}/${{ var.REPO_NAME }}:${{ github.sha }}"
