name: Maven build plan
on: 
  workflow_dispatch
jobs:
  build:
   runs-on: self-hosted
   steps:
     - name: checkout git
       uses: actions/checkout@v3
  package:
   runs-on: self-hosted
   steps:
     - name: maven build
       run: mvn package
   
